robots:
    path: /robots.txt
    controller: App\Controller\RobotsController::robots

sitemap:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::sitemap

home:
    path: /
    controller: App\Controller\HomeController::index

psychotherapy:
    path: /psychotherapie
    controller: App\Controller\PsychotherapyController::index

services:
    path: /leistungen
    controller: App\Controller\ServicesController::index

services_kvt:
    path: /leistungen/kognitive-verhaltenstherapie
    controller: App\Controller\ServicesController::kvt

services_coaching:
    path: /leistungen/coaching
    controller: App\Controller\ServicesController::coaching

services_online:
    path: /leistungen/online-therapie
    controller: App\Controller\ServicesController::onlineTherapie

services_diagnostik:
    path: /leistungen/diagnostik
    controller: App\Controller\ServicesController::diagnostik

services_diagnostik_bdi:
    path: /leistungen/diagnostik/bdi-ii
    controller: App\Controller\ServicesController::diagnostikBdi

services_diagnostik_scid:
    path: /leistungen/diagnostik/scid-5-spq
    controller: App\Controller\ServicesController::diagnostikScid

services_diagnostik_scl:
    path: /leistungen/diagnostik/scl-90
    controller: App\Controller\ServicesController::diagnostikScl

services_diagnostik_ctq:
    path: /leistungen/diagnostik/ctq
    controller: App\Controller\ServicesController::diagnostikCtq

costs:
    path: /kostenuebernahme
    controller: App\Controller\CostsController::index

about:
    path: /zur-person
    controller: App\Controller\AboutController::index

practice:
    path: /praxis
    controller: App\Controller\PracticeController::index

contact:
    path: /kontakt
    controller: App\Controller\ContactController::index

contact_submit:
    path: /kontakt/senden
    controller: App\Controller\ContactController::submit
    methods: [POST]

impressum:
    path: /impressum
    controller: App\Controller\LegalController::impressum

datenschutz:
    path: /datenschutz
    controller: App\Controller\LegalController::datenschutz